on:
  pull_request: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --no-workspaces
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:20.9-alpine3.17
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --no-workspaces
      - run: npm run spelling
